# Whether the plugin should automatically install updates from dev.bukkit.org.
auto-update: true

# Whether there are any grouped worlds. Grouped worlds save only one location per user.
enable-world-groups: false
world-groups:
  example:
    - exampleworld
    - exampleworld2
  example2:
    - exampleworld3
    
# Worlds into which players lacking the gobetween.admin permission will be disallowed from teleporting using /go.
ignored-worlds:
  - exampleworld4